---

- name: read Formula file
  slurp:
    src: "{{ formula_path }}/{{ current_dependent_formula }}"
  register: current_formula_file

- name: "reset current formula revision"
  set_fact:
    current_formula_revision: 0

- name: "read current formula revision from file"
  set_fact:
    found_formula_revision: "{{ current_formula_file['content'] | b64decode | regex_findall('revision (.+)') }}"

- name: override defautlt revsision number
  set_fact:
    current_formula_revision: "{{ found_formula_revision | first }}"
  when: found_formula_revision is defined and found_formula_revision | length > 0

- name: increase formula revision
  set_fact:
    increased_formula_revision: "{{current_formula_revision|int + 1 }}"

- name: "update or add revision to formula"
  lineinfile:
    path: "{{ formula_path }}/{{ current_dependent_formula }}"
    firstmatch: yes
    insertafter: "  url "
    regexp: '^(.*)revision(.*)$'
    line: '  revision {{ increased_formula_revision }}'