---

- name: Include build information file
  include_vars:
    file: "{{ build_info_file }}"
    name: "buildinfo"

- name: Extract build information to vars
  include_tasks: tasks/extract-buildinfo.yml

- name: Replace botte information in formula file
  replace:
    path: "{{ formula_path }}/{{ formula_name }}.rb"
    regexp: "{{ bottle_os }}: (.+)"
    replace: "{{ bottle_os }}: \"{{ bottle_sha256 }}\""
