---

- name: Include build information file
  include_vars:
    file: "{{ build_info_file }}"
    name: "buildinfo"

- name: Extract build information to vars
  include_tasks: tasks/extract-buildinfo.yml

- name: Delete existing bottle on bintray
  uri:
    url: "{{ bintray_base_url }}/{{ bottle_filename }}"
    user: "{{ bintray_user }}"
    password: "{{ bintray_key }}"
    method: DELETE
    force_basic_auth: yes
    status_code: 200
  ignore_errors: yes 

- name: Upload bottle to bintray
  uri:
    url: "{{ bintray_package_url }}/{{ bottle_filename }}"
    user: "{{ bintray_user }}"
    password: "{{ bintray_key }}"
    method: PUT
    src: "{{ build_path }}/{{ bottle_local_filename }}"
    force_basic_auth: yes
    status_code: 201

- name: Publish bottle on bintray
  uri:
    url: "{{ bintray_package_publish_url }}"
    user: "{{ bintray_user }}"
    password: "{{ bintray_key }}"
    method: POST
    body_format: json
    body: 
      discard: "false"
    force_basic_auth: yes
    status_code: 200