---

- name: Include build information file
  include_vars:
    file: "{{ build_info_file }}"
    name: "buildinfo"

- name: Extract build information to vars
  include_tasks: tasks/extract-buildinfo.yml

- name: Delete existing bottle on bintray
  uri:
    url: "{{ bintray_base_url }}/{{ bottle_filename }}"
    user: "{{ bintray_user }}"
    password: "{{ bintray_key }}"
    method: DELETE
    status_code: 200

- name: Upload bottle to bintray
  shell: 
    curl -T {{ bottle_local_filename }} -u{{ bintray_user }}:{{ bintray_key }} {{ bintray_package_url }}/{{ bottle_filename }}

- name: Publish bottle on bintray
  uri:
    url: "{{ bintray_package_publish_url }}"
    user: "{{ bintray_user }}"
    password: "{{ bintray_key }}"
    method: POST
    body: "{ \"discard\": \"false\" }"
    body_format: json
    status_code: 200