language: generic

os: osx

osx_image:
  - xcode10.2
  - xcode11.2

addons:
  homebrew:
    packages:
      - jq
    update: true

jobs:
  include:
    - stage: build bottles => :catalina
      osx_image: xcode11.2
      env:
        - OS=catalina
      script:
        - bash scripts/travisbuild
    - stage: build bottles => :mojave
      osx_image: xcode10.2
      env:
        - OS=mojave
      script:
        - bash scripts/travisbuild

if: |
  commit_message =~ /^\[build\]/ AND \
  branch = master AND \
  type = push
