os: osx
osx_image:
  - xcode10.2
addons:
  homebrew:
    update: true
jobs:
  include:
    - stage: build nginx
      osx_image: xcode10.2
      env:
        - OS=mojave
      script:
        - bash scripts/travisbuild nginx
      if: |
        commit_message =~ /(^\[build\]|nginx/ AND \
        branch = master AND \
        type = push
