language: generic

stages:
  - build-catalina
  - build-mojave

os: osx

osx_image:
  - xcode10.2
  - xcode11.2

addons:
  homebrew:
    packages:
      - jq
    update: true

jobs:
  include:
    - stage: build-catalina
      osx_image: xcode11.2
      env:
        - OS=catalina
      script:
        - while sleep 5m; do echo "=====[ $SECONDS seconds, buildroot still building... ]====="; done &
        - scripts/travisbuild
        - kill %1
    - stage: build-mojave
      osx_image: xcode10.2
      env:
        - OS=mojave
      script:
        - while sleep 5m; do echo "=====[ $SECONDS seconds, buildroot still building... ]====="; done &
        - scripts/travisbuild
        - kill %1

if: |
  commit_message =~ /^\[build\]/ AND \
  branch = master AND \
  type = push
