trigger:
- master

strategy:
  matrix:
    mojave:
      imageName: 'macOS-10.14'
    highsierra:
      imageName: 'macOS-10.13'

pool:
  vmImage: $(imageName)

steps:

- script: |
    python -m pip install --upgrade pip
    pip install -Iq -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    ansible-playbook playbooks/build-bottles.yml
  workingDirectory: .github/ansible
  displayName: 'Build bottles'
