trigger:
- master

jobs:
- job: build_bottles
  pool:
    vmImage: 'macOS-10.14'
  steps:

  - script: |
      pip install --upgrade pip
      pip install -Iq -r requirements.txt
    workingDirectory: .github/ansible
    displayName: 'Install dependencies'

  - script: |
      ansible-playbook playbooks/build-bottles.yml
    workingDirectory: .github/ansible
    displayName: 'Build bottles'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'build'
      artifact: 'build'
      publishLocation: 'pipeline'

- job: upload_bottles
  dependsOn: build_bottles
  pool:
    vmImage: 'macOS-10.14'
  steps:

  - script: |
      brew update
      brew upgrade
      pip install --upgrade pip
      pip install -Iq -r requirements.txt
    workingDirectory: .github/ansible
    displayName: 'Install dependencies'

  - task: DownloadPipelineArtifact@1
    inputs:
      buildType: 'current'
      artifactName: 'build'
      targetPath: '$(System.DefaultWorkingDirectory)/build'

  - script: |
      ansible-playbook playbooks/upload-bottles.yml
    env:
      BINTRAY_USER: $(BINTRAY_USER)
      BINTRAY_KEY: $(BINTRAY_KEY)
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    workingDirectory: .github/ansible
    displayName: 'Upload bottles'
 
- job: update_fomulae
  dependsOn: upload_bottles
  pool:
    vmImage: 'macOS-10.14'
  steps:

  - script: |
      pip install --upgrade pip
      pip install -Iq -r requirements.txt
    workingDirectory: .github/ansible
    displayName: 'Install dependencies'

  - task: DownloadPipelineArtifact@1
    inputs:
      buildType: 'current'
      artifactName: 'build'
      targetPath: '$(System.DefaultWorkingDirectory)/build'

  - script: |
      ansible-playbook -vvv playbooks/update-formulas.yml
    env:
      GITHUB_ACTOR: "ci"
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      GITHUB_REPOSITORY: "valet-sh/homebrew-core"
    workingDirectory: .github/ansible
    displayName: 'Update Formulae'