trigger:
- master

jobs:
- job: build_bottles
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      git show --pretty="" --name-only HEAD
    displayName: "Test git"

  - script: |
      pip install --upgrade pip
      pip install -Iq -r requirements.txt
    workingDirectory: .github/ansible
    displayName: 'Install dependencies'

  - script: |
      ansible-playbook playbooks/build-bottles.yml
    workingDirectory: .github/ansible
    displayName: 'Build bottles'

  - publish: build
    artifact: build

- job: upload_bottles
  dependsOn: build_bottles
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - download: ./
    artifact: build

  - script: |
      ls -lsa
      ls -lsa build
 