---

- hosts: local
  gather_facts: True

  tasks:
    - name: "get github timestamp filter"
      shell: "date -d '6 hour ago' --utc +%FT%TZ"
      register: github_commit_filter_timestamp_obj

    - name: "prepare var 'github_commit_filter_timestamp'"
      set_fact:
        github_commit_filter_timestamp: "{{ github_commit_filter_timestamp_obj.stdout }}"

    - name: check for formula dependencies
      include_tasks: tasks/flag-formula.yml
      with_items: "{{ github_commit_filter }}"
      loop_control:
        loop_var: github_commit_filter_item

