---

base_path: "../../.."
build_path: "{{ base_path }}/build"
formula_path: "{{ base_path }}/Formula"

git_author_name: "GitHub Actions"
git_author_email: "actions@github.com"

github_token: "{{ lookup('env','GITHUB_TOKEN') }}"
github_repository_url: "https://{{ github_token }}@github.com/valet-sh/homebrew-core.git"

bintray_base_url: "https://api.bintray.com/content/valet-sh/homebrew-core"
bintray_package_url: "{{ bintray_base_url }}/core/core"
bintray_package_publish_url: "{{ bintray_package_url }}/publish"
bintray_key: "{{ lookup('env','BINTRAY_KEY') }}"
bintray_user: "{{ lookup('env','BINTRAY_USER') }}"
