name: build

on:
  push:
    paths:
    - 'Formula/**.rb'

jobs:

  build-bottles:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: macOS-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: .github/ansible
        run: |
          brew update
          brew upgrade
          python -m pip install --upgrade pip
          pip install -Iq -r requirements.txt

      - name: Build bottles
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        working-directory: .github/ansible
        run: ansible-playbook playbooks/build-bottles.yml

      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: build


  upload-bottles:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    needs: [build-bottles]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: .github/ansible
        run: |
          python -m pip install --upgrade pip
          pip install -Iq -r requirements.txt

      - uses: actions/download-artifact@v1
        with:
          name: build

      - name: Upload Bottles
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/ansible
        run: ansible-playbook playbooks/upload-bottles.yml


  update-formulas:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    needs: [upload-bottles]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - uses: actions/checkout@v1

      - name: Install dependencies
        working-directory: .github/ansible
        run: |
          python -m pip install --upgrade pip
          pip install -Iq -r requirements.txt

      - uses: actions/download-artifact@v1
        with:
          name: build

      - name: Update Formulas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: .github/ansible
        run: ansible-playbook playbooks/update-formulas.yml

