name: CI

on: [push]

jobs:
  prepare:
    runs-on: [ubuntu-latest]
    steps:
    - run: echo "revision 54" > /github/test.txt

  test:
    runs-on: [ubuntu-latest]
    steps:
    - run: cat /github/test.txt
  
  build-catalina:
    runs-on: macOS-latest
    env:
      OS: catalina
    steps:
    - uses: actions/checkout@master
    - name: Run build script
      working-directory: ${{ github.workspace }}
      run: scripts/actionsbuild

  build-mojave:
    runs-on: macOS-10.14
    env:
      OS: mojave
    steps:
    - uses: actions/checkout@master
    - name: Run build script
      working-directory: ${{ github.workspace }}
      run: scripts/actionsbuild
